num_gpu: 2
basedir: ./logs
datadir: ./data/nerf_synthetic/lego
tbdir: ./logs_tb
dataset_type: blender

# Training option
N_rand: 1024
N_samples: 64
N_importance: 64
N_iters: 300000
lrate: 5.0e-4
lrate_decay: 250

no_ndc: True
lindisp: True
spherify: True

i_print: 1000
i_weights: 20000
i_testset: 50000
i_video: 50000

# data option
half_res: False

# NeRF option
use_viewdirs: True
raw_noise_std: 1.0e-0
rgb_activate: sigmoid
